language: node_js
node_js:
- "14"

services: mongodb

install:
    - npm install
before_script:
    - mongo mern-db-test --eval 'db.createUser({user:"myuser",pwd:"mypassword",roles:["admin"]});'
script:
    - export DATABASE_URL=mongodb://myuser:mypassword@localhost/mern-db-test?authSource=admin
    - export APP_PORT=4000
    - export TEST_SUITE=mern-db-test?authSource=admin
    - jest --verbose --detectOpenHandles --coverage && coveralls < coverage/lcov.info