language: node_js
node_js:
- "14"

services: mongodb

install:
    - npm install
script:
    - export DATABASE_URL=mongodb:/localhost:27017/mern-db-test
    - export APP_PORT=4000
    - export TEST_SUITE=mern-db-test?authSource=admin
    - jest --verbose --detectOpenHandles --coverage && coveralls < coverage/lcov.info