module.exports = {
    PORT: process.env.APP_PORT,
    // TODO REMOVE 0.0.0.0 THIS WHEN DOCKERIZING APP
    // REPLACE 0.0.0.0 WITH MONGO WHEN EVERYTHING IS IN THE SAME NETWORK
    // AND ALSO REMOVE PORTS FROM DOCKER COMPOSE BECAUSE IT WONT BE NECESSARY
    DB: process.env.DATABASE_URL
}